services:
  api:
    build: .
    container_name: api_fast_scholl
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data: